### ISSUE TITLE
Body Mode results in crash if started immediately

### ISSUE THREAD

**Issue by steven-t-h** [YUNEEC/Yuneec-SDK-iOS-Example#6]
@julianoes I've been experimenting with creating some sample apps using the iOS SDK and came across an issue I'm seeing in this application as well. If I try to initiate Offboard while in Body mode the unit immediately flips and crashes. However, if I start offboard in NED then switch I don't have this issue.

Any ideas?

**Comment by julianoes** [comment]
@steven-t-h Fix coming up!

**Comment by julianoes** [comment]
This has been resolved, closing.
